### ISSUE TITLE
Lack of animated models

### ISSUE THREAD

**Issue by LowkeyFL** [Redi2Go/PhotonicEngine#102]
I've noticed this, and I'm pretty sure the devs have too, so I'll just say it to be sure:

Only a few models ended up being animated, if not just one: The sculk sensor.

I've found it quite sad none of the models had any working animations so far, so I wanted to ask: Would other models (Fire, chests, stonecutter, etc. ) Be animated, and will there be support for custom animations?

(I did not know where else to say this, do correct me if needed)

**Comment by Redi2Go** [comment]
Will be indirectly fixed with the next release :]

**Comment by Redi2Go** [comment]
Fixed with the new release
