### ISSUE TITLE
1.21.1 mod isnt working

### ISSUE THREAD

**Issue by bristerypunto** [Redi2Go/PhotonicEngine#104]
mod doesnt work for me in 1.21.1, but it does in 1.20.6, i launch the game and i see the normal shaders, but not the rtx as in 1.20.6

**Comment by Redi2Go** [comment]
You need to activate "BSL [PHOTONICS] " as a shader

**Comment by georgemckornis** [comment]
doesnt work there is no "BSL [PHOTONICS]"
