### ISSUE TITLE
No raytraced/pathtraced shadows in-game as promised

### ISSUE THREAD

**Issue by oisintheblue** [Redi2Go/PhotonicEngine#113]
![2024-12-05_18 02 55](https://github.com/user-attachments/assets/d4b9b62a-e089-4623-9ed0-2dfab04e3d0e)

how the heck am i supposed to get the GI and shadows from light sources n stuff like in the pictures on the modrinth page? i have the exact version of BSL shaders, and i use 1.21.1 fabric

**Comment by oisintheblue** [comment]
the only shadows that appear is the shadows from the sun (idrk how to properly word this)

**Comment by oisintheblue** [comment]
oh wait... i'm stupid-
a photonics version of BSL appears in my shaderpack folder and now everything works as intended! one suggestion i would make is to make it so that if you are further away enough from a 3d object (one that in vanilla minecraft, is usually 2d.) it changes into a 2d object to reduce lag

**Comment by TNT4ME** [comment]
That is kinda how distant horizons works. Idk if that can be done in a shader or not.

**Comment by Redi2Go** [comment]
Thanks for the recommendation, I'm working on a rewrite of the engine that incorporates further optimizations

**Comment by georgemckornis** [comment]
theres no bsl that appeared its just the one that i downloaded all dependencies are downloaded
