### ISSUE TITLE
No chest opening animation

### ISSUE THREAD

**Issue by TMGITA** [Redi2Go/PhotonicEngine#16]
No chest opening animation

**Comment by Felix14-v2** [comment]
I believe this is intended since the chest model renders as a block, when in vanilla it is a tile entity.

**Comment by Redi2Go** [comment]
Correct, only static terrain that is considered during Chunk Building is actually raytraced. Everything else will have to be done using rasterization (Entities, animated BlockTiles, Particles, ...)
