### ISSUE TITLE
Redstone lamps do not emit light

### ISSUE THREAD

**Issue by estebangames842** [Redi2Go/PhotonicEngine#27]
Nothing else but the mod and dependencies installed 
![image](https://github.com/Redi2Go/PhotonicEngine/assets/36859022/ae1cbf10-61d8-41a6-94d9-55da8ad421f1)

Redstone lamps do not emit light, tried with both multithreading on and off

**Comment by Redi2Go** [comment]
Thanks for reporting! Upcoming release fixes that (together with Lava not emitting light)
