### ISSUE TITLE
Screen is just two colors

### ISSUE THREAD

**Issue by Oregano1963** [Redi2Go/PhotonicEngine#30]
Logs: https://mclo.gs/FQ54yjt

Photo: 
![2024-07-09_22 08 45](https://github.com/Redi2Go/PhotonicEngine/assets/159829604/836b920a-045b-4410-81ad-e8bf969e5ff0)

Using Mint as the OS.

**Comment by Redi2Go** [comment]
Thank you for reporting! Do shaders work without Photonics installed? As is seems not even the sky is rendered (which is solely managed by Iris/BSL).

**Comment by Oregano1963** [comment]
Shaders work fine on a separate instance without photonics

**Comment by Redi2Go** [comment]
Ok, I'll see if I can reproduce the bug

**Comment by Oregano1963** [comment]
It seems to happen with just bsl without photonics

**Comment by Redi2Go** [comment]
....so you suspect that the root cause lies within BSL? 
The mod works fine on my Kubuntu installation with Nvidia drivers.
