### ISSUE TITLE
Request: chunk render distance limit increase

### ISSUE THREAD

**Issue by mschievousmadi** [Redi2Go/PhotonicEngine#38]
First, you've built a gorgeous mod here and I love it <3 

Small (maybe?) request though: I noticed that the render distance slider is capped at 8 chunks, which is fine for performance, but I'm really interested in seeing how the world would look if we could render 16-32 chunks if possible!

**Comment by Redi2Go** [comment]
Thank you for your very kind words! <3
I'm actually currently working on adding proper Distant Horizons support. But the *actual* raytraced world is capped at 256x256x256 blocks (for math reasons). But you can try DH right now (with poor support)

**Comment by Redi2Go** [comment]
I have restructured some code and I managed to increase the render distance to 15 chunks. The next release is going to need a few days, though.
