### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by usermaf** [Redi2Go/PhotonicEngine#4]
Allow for shader configuration.

**Comment by Redi2Go** [comment]
Thank you for reaching out! Any concrete ideas?

**Comment by usermaf** [comment]
Settings inside the mod configs for Shadow penumbra/cone angle, water roughness, water reflection intensity, skylight intensity, sunlight intensity, water parallax strength/freq, block light intensity, and denoiser on/off.

**Comment by Redi2Go** [comment]
I've added them to my TODO list (which is getting quite long).Thank you for your feedback!
