### ISSUE TITLE
Last update does not work

### ISSUE THREAD

**Issue by ciaens** [Redi2Go/PhotonicEngine#42]
Hello,

I downloaded the updated mod 0.2.2 and it does not work anymore. I crash every time I join a world.

Error in question : 
[09:39:28] [Render thread/INFO]: [STDERR]: Link info
---------
error: interpolation modifier mismatch for varying parameter (named sunVecWorld) between shader stages

====================

Le processus a cessé de fonctionner avec le code de sortie -1073740791.

My mods :
Mods:
  [✔] fabric-api-0.100.8+1.20.6
  [✔] iris-1.7.2+mc1.20.6
  [✔] modmenu-10.0.0
  [✔] no-telemetry-1.8.0
  [✔] Photonic-0.2.2
  [✔] placeholder-api-2.4.0-pre.1+1.20.5
  [✔] sodium-fabric-0.5.11+mc1.20.6

System : Windows 11, Ryzen 5000 CPU, NVIDIA GPU.

Full logs : 
https://mclo.gs/zvsKwpz

Previous version is working (confirmed by downgrading the mod).

**Comment by Redi2Go** [comment]
Thank you for reporting this issue. This will be fixed until tomorrow.

**Comment by Redi2Go** [comment]
New release is out!
Can you please verify, that the bug is fixed?

[https://modrinth.com/mod/photonics/version/0.2.2](https://modrinth.com/mod/photonics/version/0.2.2)

**Comment by nitanmarcel** [comment]
> New release is out! Can you please verify, that the bug is fixed?
> 
> https://modrinth.com/mod/photonics/version/0.2.2

I had the same issue as the OP, the game does launch now without any issues
