### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by Oregano1963** [Redi2Go/PhotonicEngine#44]
Report: https://mclo.gs/EjhWQ7O

after updating photonics and fabric, I can no longer enter a world. I redownloaded the mod and BSL and got the same crash about compiling shaders.

**Comment by Redi2Go** [comment]
Should be fixed with the new release 0.2.3, please validate

**Comment by Oregano1963** [comment]
Well I can enter the world but the issue I posted before about the screen being two colors persists
