### ISSUE TITLE
Glitched out graphics

### ISSUE THREAD

**Issue by Oregano1963** [Redi2Go/PhotonicEngine#45]
The BSL shader issue could be resolved by disabling the light shafts but now the graphics are glitched out--though surprisingly enough, entities don't seem to be affected. 

![2024-08-16_00 09 59](https://github.com/user-attachments/assets/7df90e2d-914e-41f2-9a20-2e36c89cdea2)

I'm using the 7900XTX with mesa 24.1.3

logs: https://mclo.gs/47mBe4l

**Comment by Oregano1963** [comment]
Oh yeah. And there are phantom oak logs everywhere and the oak logs that actually are there look white. Not sure if these are related

**Comment by Redi2Go** [comment]
I will try to reproduce the bug today. Can you please verify the specs:
- 7900 XTX
- mesa 24.1.3
- Linux Mint version ???

**Comment by Oregano1963** [comment]
21.3 cinnamon
6.8.0-40-generic kernel

the rest is correct

**Comment by Redi2Go** [comment]
Im getting similar rendering issues using Linux Mint and AMDGPU drivers. I'm currently working on fixing those issues.

**Comment by Oregano1963** [comment]
Good to know

**Comment by Redi2Go** [comment]
So, the Light Shafts is definitely an issue on the BSL side, the artifacts seen on all the blocks (not entities) are Photonics' fault. 

Please try out the version attached
[Photonic-0.tar.gz](https://github.com/user-attachments/files/16644459/Photonic-0.tar.gz)

**Comment by Oregano1963** [comment]
it works now
