### ISSUE TITLE
Not rendering correctly, screen is made up of only two colors

### ISSUE THREAD

**Issue by Fxsch** [Redi2Go/PhotonicEngine#59]
### Bug description

This mod doesn't correctly render when I use it, here's a screenshot of what it looks like:
![image](https://github.com/user-attachments/assets/b0952d51-4332-4f3c-a123-0712a8355108)

The colors change when I look around. Disabling BSL makes everything look normal again but obviously disables the mod's effects too.

### Tested versions

- [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized) on MC version 1.21.1
- MC version 1.21.1 with just Photonics and its dependencies
- [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized) on MC version 1.20.6 with Photonics version 0.2.3

I also always used BSL version 8.2.09

### Hardware/Software configuration

**OS**: Fedora Linux 40
**Java version**: OpenJDK 21
**GPU**: AMD Radeon RX 6700 XT
**CPU**: AMD Ryzen 7 7800X3D
**GPU driver**: Mesa 24.1.7

**Comment by awumii** [comment]
BSL shaders are broken in Mesa 24.1, you need to upgrade to Mesa 24.2 which fixed this issue.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11364

**Comment by Fxsch** [comment]
Then I'll have to wait for the new Mesa version to land in the Fedora repos. Should this issue be closed?

**Comment by Oregano1963** [comment]
probably.  You should disable light shafts in setting for the time being

**Comment by Fxsch** [comment]
The Fedora update came out yesterday and after updating the issue is gone
