### ISSUE TITLE
Align plant models to their real hitboxes

### ISSUE THREAD

**Issue by Cheesy-Brik** [Redi2Go/PhotonicEngine#62]
Currently the mod just centers every plant model. It should try to align it with it's real hitbox instead

![image](https://github.com/user-attachments/assets/b1d6ffcc-a403-41ea-8cf5-908fbf269fed)
![image](https://github.com/user-attachments/assets/f3cfc29f-0dc1-46ae-bbcb-b1b428c91c20)
![image](https://github.com/user-attachments/assets/252d900b-8120-4a0a-b2a0-4280adc4e0b4)

**Comment by Redi2Go** [comment]
Voxel-based rendering is deprecated, so this issue will not be worked on
