### ISSUE TITLE
[Feature Request] 1.20.1 support?

### ISSUE THREAD

**Issue by Anonymous-Floof** [Redi2Go/PhotonicEngine#67]
I've found that 1.20.1 is still a largely used version for mod packs, including many of the ones that I currently use
(including my custom ones).
And I'd love to see this mod compatible with that version. Not necessarily soon or as a top priority, But whenever the mod is stable and functional it'd be nice to see it support 1.20 through to the latest versions if possible

**Comment by DaBaldEagul** [comment]
+1, saw this in AsianHalfSquat's video and wanted to try the mod out on my modded server, then promptly noticed it was 1.20.6/1.21.1 only. This shouldn't be the no 1 priority, but it would be really nice :)

**Comment by Redi2Go** [comment]
Since you asked so nicely, I will try to make it happen as soon as possible :wink:

**Comment by Redi2Go** [comment]
Photonics 0.2.5 with version 0.2.5 is now available at Modrinth
