### ISSUE TITLE
Game is going insane

### ISSUE THREAD

**Issue by Dashy22** [Redi2Go/PhotonicEngine#7]
I have a pretty bad laptop but the mod runs pretty well at  around 14 fps.
But i feel like im going insane i wish i could record my screen i dont even know how to explain it and when i take out the snipping tool than the screen goes white.
When i move at all the world starts bending and flying around me and turning black and white and bright and dark  and my guy is doing backflips and the sky keeps hitting my face. But lava and animals stay still. And the world flips colors sometimes and is upside down and warps around my screen. 
Im just wondering if theres a way to fix this but i dont think this is a crazy big problem since this is rare. Im up to date for now on the mod and i have no other mods on.

**Comment by Redi2Go** [comment]
Try turning off View Bobbing, I messed up some logic on the latest release.
Also, go to Video Settings and set the Fullscreen resolution to the lowest setting. When pressing F11 the game should go to Fullscreen at a low resolution and FPS should increase.

**Comment by Dashy22** [comment]
That fixed the warping but the world is flashing from pitch dark to bright(only the blocks). And the skybox has weird squares edges that are white. Im guessing it could be a sky box problem since im using dramatic skys which is animated but im not sure.

**Comment by Redi2Go** [comment]
A screenshot would be great (F2). But I'm working on removing Skyboxes anyway on the next release. Thanks!

**Comment by Dashy22** [comment]
[Here's 3 Photos, It was hard to take a photo of the forest in pure darkness since it was randomly pulsing whenever I moved.](https://imgur.com/a/AxOD9tz)

**Comment by Dashy22** [comment]
Those were photos after the solution you said

**Comment by Dashy22** [comment]
[These are some photos i took while the weird mode was on before you solution.](https://imgur.com/a/CNMVOeF)

**Comment by Redi2Go** [comment]
I'd suggest sticking to Awesome Skies for now, the next release that fixes the skybox will take some time, tough.
