### ISSUE TITLE
Redstone Lamp still emits light after being turned off

### ISSUE THREAD

**Issue by Cat-Gaming** [Redi2Go/PhotonicEngine#70]
When you place a Redstone lamp in a dark room or cave and turn it on, it still emits light after being turned off. Photonic Version 0.2.4
![2024-10-27_12 46 49](https://github.com/user-attachments/assets/30ebcf36-9e0a-4799-9d52-67439e656414)

**Comment by Redi2Go** [comment]
Should be fixed with 0.2.5
