### ISSUE TITLE
Not rendering, all block are transparent.

### ISSUE THREAD

**Issue by encra** [Redi2Go/PhotonicEngine#72]
![2024-10-27_21 28 15](https://github.com/user-attachments/assets/19985d39-1fb3-45a5-8681-4ae48ebf3858)
![2024-10-27_21 28 07](https://github.com/user-attachments/assets/bee5f4ef-6822-4e0d-8f4f-6abd19196be3)

When i enable the shader all blocks becomes transparent. I tried 1.20.6 version to , same thing happens.

Mods:
fabric-api-0.107.0+1.21.1
iris-1.7.3+mc1.21
modmenu-11.0.3
Photonic-0.2.4
sodium-fabric-0.5.11+mc1.21

Hardware / Software:
OS: Windows 10 22H2 (KB5045991)
Java: Version 8 Update 431
GPU Driver: GeForge Game Ready 566.03
GPU: RTX 3080
CPU: i5 12400F

**Comment by kxxzo** [comment]
If you have custom BSL settings, try backing up it and reset your settings

**Comment by encra** [comment]
> If you have custom BSL settings, try backing up it and reset your settings

Tried it, not working

**Comment by Redi2Go** [comment]
Are there any errors in the logs? How long have you waited for the blocks to load? Thanks!

**Comment by encra** [comment]
I tried it again, waited about 10-15 min. 

Here is the logs:
[2024-10-29-3.log](https://github.com/user-attachments/files/17593713/2024-10-29-3.log)

**Comment by encra** [comment]
> Are there any errors in the logs? How long have you waited for the blocks to load? Thanks!

I tried it again, waited about 10-15 min.

Here is the logs:

[latest.log](https://github.com/user-attachments/files/17593757/latest.log)

**Comment by Anonymous-Floof** [comment]
Yeah, I'm having the same issue. Everything is just transparent for some reason XD

**Comment by Anonymous-Floof** [comment]
> Yeah, I'm having the same issue. Everything is just transparent for some reason XD

Nevermind, I found a fix?
All I did was force reset the shader to defaults in the shader options screen.
No idea how that worked, as I never changed anything lol
