### ISSUE TITLE
incompatible with iris version 1.8.0-beta

### ISSUE THREAD

**Issue by StroepWafel** [Redi2Go/PhotonicEngine#73]
when i launch this mod i get the following error:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Photonic' (photonics) 0.2.4 with any version that is compatible with:
		 - iris 1.8.0-beta.4+mc1.21.1
More details:
	 - Mod 'Photonic' (photonics) 0.2.4 requires version 1.7.3+1.21 of mod 'Iris' (iris), but only the wrong version is present: 1.8.0-beta.4+mc1.21.1!

**Comment by Redi2Go** [comment]
You need to use [Iris 1.7.3](https://modrinth.com/mod/iris/version/1.7.3+1.21)

Iris 1.7.3
Sodium 0.5.11
Mod menu 11.0.0
