### ISSUE TITLE
3D blocks aren't working, and photonics doesn't show up in the shader list.

### ISSUE THREAD

**Issue by nobz99** [Redi2Go/PhotonicEngine#74]
When using the mod, I get great performance, which means it's working. But I am not seeing any 3D blocks, and in my shaders menu the photonics version of BSL doesn't show up as an option, only the original BSL.

**Comment by nobz99** [comment]
I have figured out that it is an issue with the newest version. I have gone to earlier versions and they work just fine.

**Comment by Redi2Go** [comment]
You need the excact version of [BSL v8.2.09](https://modrinth.com/shader/bsl-shaders/version/8.2.09)

If it still doesn't show up, could you please tell me the excact name of the Shaderpack in your Shader Selection list
