### ISSUE TITLE
Documentation on how to add custom block models

### ISSUE THREAD

**Issue by TNT4ME** [Redi2Go/PhotonicEngine#79]
In the mod's [Modrinth](https://modrinth.com/mod/photonics) page, it is mentioned that custom block models can be added using [Magicavoxel](https://ephtracy.github.io/). However there is no documentation/steps on how to do so.

**Comment by Redi2Go** [comment]
Voxel-based rendering is deprecated and will be replaced with a traditional triangle-based rendering. Custom block models with Magicavoxel will not be possible in the future
