### ISSUE TITLE
dynamic lights dont light up entities when in hand

### ISSUE THREAD

**Issue by space2ninja101** [Redi2Go/PhotonicEngine#81]
the last 1.20.6 version worked fine but 2.4.0 all entities are black when dynamic lights like torches are held
even the player
only if its placed it lights up entities
this is either my fault or the mods fault
anyone get this issue?

issue im describing: 
![image](https://github.com/user-attachments/assets/a8638513-9d02-4cda-b767-b266c84e8366)

when placed:
![image](https://github.com/user-attachments/assets/5bd34f11-4feb-4111-91a4-1b586f5e16de)

maybe implement entity voxelization?

**Comment by space2ninja101** [comment]
i have a suspicion this might be an entity culling conflict, going to try without it

**Comment by space2ninja101** [comment]
nope didnt fix

**Comment by Redi2Go** [comment]
Thanks for your feedback :)

It's a known bug: https://github.com/Redi2Go/PhotonicEngine/issues/49
