### ISSUE TITLE
Minecraft gets stuck on the initial loading screen when Photonic is enabled

### ISSUE THREAD

**Issue by Butterscotch-P1e** [Redi2Go/PhotonicEngine#82]
<img width="731" alt="Screenshot 2024-11-06 at 3 56 30 PM" src="https://github.com/user-attachments/assets/372d0044-19c4-4cf6-81f6-0c4791fd9b0d">

**Comment by Redi2Go** [comment]
Hi! Are there any logs? What are your system specs?

**Comment by noisereduced** [comment]
same happens to me, I can hear and click menu options though I cannot see anything it jut shows the loading screen.
unsure about OP but I am on a macbook air (m1 cpu/gpu, 8gb ram)

**Comment by Butterscotch-P1e** [comment]
Yeah it might just be a MacOS thing. I doubt M1 is anywhere near powerful enough but it would’ve been funny to see it struggle. M3 and M4 could totally do it though. I'm also on a base model M1 Air. I also have a Mac Mini that's the same but with 16GB of RAM instead incase it's a RAM issue. Doubt it.

**Comment by adumeige** [comment]
Is that the same as https://github.com/Redi2Go/PhotonicEngine/issues/68 ?

**Comment by Redi2Go** [comment]
If the logs state something like "VERSION 430 not supported", then yes
