### ISSUE TITLE
Photonics is built for 1.21.4 instead of 1.21.3

### ISSUE THREAD

**Issue by Nadanoob99** [Redi2Go/PhotonicEngine#91]
Currently the newest Minecraft version is 1.21.3, so there must be a typo.
![image](https://github.com/user-attachments/assets/3381c835-642e-4920-a64a-e776be13d6a4)

**Comment by ImSapphire** [comment]
That says 1.20.4

**Comment by Nadanoob99** [comment]
Sorry, I didn't realize that.
