### ISSUE TITLE
Please, don't get rid of voxelated render

### ISSUE THREAD

**Issue by adumeige** [Redi2Go/PhotonicEngine#92]
Sorry, not really an issue, but can't find discord or other kind of free exchange medium.

I **love** the voxel render and it's the main draw for me. Is it possible to have it separated rather than just removed ? Maybe the community could help ?

Anyway, fantastic job on photonic !

**Comment by Redi2Go** [comment]
If you like the "3D look", I can recommend the Vanilla PBR resource pack with BSL's parallax mapping (which will also work with future Photonics versions)

If you like to chat, you can always contact me via Twitter
