### ISSUE TITLE
Mob Skulls Voxelating Despite Already Being 3D 

### ISSUE THREAD

**Issue by Doc-Cynthetic** [Redi2Go/PhotonicEngine#98]
![Screenshot 2024-11-10 223114](https://github.com/user-attachments/assets/a568c972-ca4f-4030-bd7a-2b4ec7355a02)

This does not seem to occur with player heads in the same manner, and only affects vanilla skulls from skeletons etc.
I hope these help!

**Comment by Redi2Go** [comment]
Good catch! That's an oversight on my part. Since 3D rendering will be replaced with the next release, I won't be working on this issue.

Thank you for reporting, though!
