### ISSUE TITLE
Entity is not rendered correctly when handling light source

### ISSUE THREAD

**Issue by kxxzo** [Redi2Go/PhotonicEngine#99]
![2024-11-11_16 40 00](https://github.com/user-attachments/assets/a08f5dac-df85-471a-affc-faa19981bab0)
![2024-11-11_16 39 58](https://github.com/user-attachments/assets/dc2de9a1-1480-4a8a-9fd4-f89d25d33428)

- **Photonics** <sub>_(Latest Version)_</sub>
- **Mod Menu** <sub>_(Latest Version)_</sub>
- **Fabric API** <sub>_(Latest Version)_</sub>
- **BSL** <sub>_(v8.2.09)_</sub>

**Comment by Redi2Go** [comment]
Hi, thank you for reporting. I have this bug already on my radar :)

Duplicate of #51
